services:
  backend_course_2:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: backend_course_2
    ports:
      - "8000:8000"
    labels:
      - "portless.primary=true"
      - "portless.domain=api.course.test"
    volumes:
      - .:/app

    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload