[project]
name = "backend-course"
version = "0.1.0"
description = "Project where I study backend with fastapi and a course from udemy"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "fastapi>=0.139.2",
    "fastapi-users>=15.0.5",
    "pydantic[email]>=2.13.4",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.48,<2.1",
    "uvicorn[standard]>=0.51.0",
]


[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "ruff>=0.15.16",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "fastapi.Path"]


